# Generated by Django 3.2.17 on 2023-10-19 12:13

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql=f'CREATE SCHEMA IF NOT EXISTS django;',
                        # f"SET search_path TO django;",
                    reverse_sql='DROP SCHEMA IF EXISTS django CASCADE',
                ),
            ],
        ),
    ]
