# Generated by Django 3.2.17 on 2023-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.CharField(blank=True, max_length=240, null=True)),
                ('hour', models.CharField(blank=True, max_length=96, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=64, null=True)),
                ('day_of_month', models.CharField(blank=True, max_length=124, null=True)),
                ('month_of_year', models.CharField(blank=True, max_length=64, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'public"."celery_crontab_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntervalScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every', models.IntegerField()),
                ('period', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'public"."celery_interval_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodicTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
                ('args', models.TextField(blank=True, null=True)),
                ('kwargs', models.TextField(blank=True, null=True)),
                ('queue', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('routing_key', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('one_off', models.BooleanField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_run_count', models.IntegerField(default=0)),
                ('date_changed', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public"."celery_periodic_task',
                'managed': False,
            },
        ),
    ]
