"""1_create_tables

Revision ID: 84d6b95e872a
Revises: 182514e6040b
Create Date: 2023-10-21 18:26:43.339441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d6b95e872a'
down_revision = '182514e6040b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=10), server_default=sa.text("'UTC+3'::character varying"), nullable=False),
    sa.Column('is_accepting_emails', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_accepting_interface_messages', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('telegram_id', sa.String(length=255), nullable=True),
    sa.Column('is_accepting_telegram', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.create_table('message',
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('to_user_uuid', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['to_user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_uuid'), 'message', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_uuid'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
