"""2_message.priority

Revision ID: 97d26e65da1d
Revises: 84d6b95e872a
Create Date: 2023-10-24 19:30:24.650137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97d26e65da1d'
down_revision = '84d6b95e872a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('priority', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_message_priority'), 'message', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_priority'), table_name='message')
    op.drop_column('message', 'priority')
    # ### end Alembic commands ###
